refugio/apps/mascota/urls.py
from django.conf.urls import url, include
from apps.mascota.views import index, mascota_view, mascota_list, mascota_edit, mascota_delete, \
 MascotaList, MascotaCreate, MascotaUpdate, MascotaDelete

from.import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
#Funciones
   url(r'^crear$', mascota_view, name='mascota_crear'),
   url(r'^lista$', mascota_list , name='mascota_lista'),
   url(r'^modificar/(?P<id_mascota>\d+)/$', mascota_edit, name='mascota_modificar'),
   url(r'^eliminar/(?P<id_mascota>\d+)/$', mascota_delete, name='mascota_eliminar'),
#Clases
   url(r'^nuevo$', MascotaCreate.as_view() , name='mascota_nuevo'),
   url(r'^listar$', MascotaList.as_view(), name='mascota_listar'),
   url(r'^editar/(?P<pk>\d+)/', MascotaUpdate.as_view(), name='mascota_editar'),
   url(r'^delete/(?P<pk>\d+)/', MascotaDelete.as_view(), name='mascota_delete'),     
]

refugio/refugio/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
#from home import views 

urlpatterns = [

    url('admin/', admin.site.urls),
    #url('home/', home, kwargs={'template_name': 'Home/index.html'}, name='home'),
    url(r'^mascota/', include('apps.mascota.urls'),name="mascota"),
    url('adopcion/', include('apps.adopcion.urls'),name="adopcion"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

refugio/apps/mascota/models.py
from django.db import models

# Create your models here.

from apps.adopcion.models import Persona

class Vacuna(models.Model):
    nombre = models.CharField(max_length=50)

    def __str__(self):
        return '{}'.format(self.nombre)

class Mascota(models.Model):
    #folio = models.CharField(max_length=10, primary_key=True)
    nombre = models.CharField(max_length=50)
    sexo = models.CharField(max_length=10)
    edad_aproximada = models.IntegerField()
    fecha_rescate = models.DateField()
    persona = models.ForeignKey(Persona, null=True, blank=True, on_delete=models.CASCADE)
    vacuna = models.ManyToManyField(Vacuna, blank=True)
    imagen = models.ImageField(upload_to="imagenes_mascota", null=False, blank=True)

refugio/apps/mascota/forms.py
from django import forms
from django.core.exceptions import ValidationError
from apps.mascota.models import Mascota
from apps.adopcion.models import Persona
import datetime
#from .models import Image

class MascotaForm(forms.ModelForm):
    
    class Meta:
    	model = Mascota 

    	fields = [
    		'nombre',
    		'sexo',
    		'edad_aproximada',
    		'fecha_rescate',
    		'persona',
    		'vacuna',
            'imagen',
    	]
    	labels= {
    		'nombre': 'Nombre',
    		'sexo': 'Sexo',
    		'edad_aproximada': 'Edad aproximada',
    		'fecha_rescate': 'Fecha de rescate',
    		'persona': 'Adoptante',
    		'vacuna': 'Vacunas',
            'imagen': 'Imagen',
    	}
    	widgets = {
    		'nombre': forms.TextInput(attrs={'class':'form-control'}) ,       
            'sexo': forms.TextInput(attrs={'class':'form-control'}),
    		'edad_aproximada': forms.NumberInput(attrs={'class':'form-control'}),
    		'fecha_rescate': forms.TextInput(attrs={'class':'form-control'}),
    		'persona': forms.Select(attrs={'class':'form-control form-select'}), 
            'vacuna': forms.CheckboxSelectMultiple(),
            'imagen': forms.ClearableFileInput(attrs={'class': 'form-control'}),
    	}

    def clean_nombre(self):
        nombremascota = self.cleaned_data.get('nombre')
        if not nombremascota:
            raise forms.ValidationError('Por favor, ingresa el nombre de la mascota')
        return nombremascota

    def clean_sexo(self):
        sexo = self.cleaned_data.get('sexo')
        valores_validos = ['macho', 'hembra']
        if not sexo or sexo.lower() not in valores_validos:
            raise forms.ValidationError('Por favor, ingresa un valor válido para el sexo: Macho o Hembra')
        return sexo

    def clean_edad_aproximada(self):
        edad_aproximada = self.cleaned_data.get('edad_aproximada')
        if not edad_aproximada:
            raise forms.ValidationError('Por favor, ingresa la edad aproximada de la mascota')
        return edad_aproximada  

    def clean_fecha_rescate(self):
        fecha_rescate = self.cleaned_data.get('fecha_rescate')
        if fecha_rescate > datetime.date.today():
            raise ValidationError("Fecha incorrecta : no puede ser mayor al dia de hoy")
        return fecha_rescate

    def clean_persona(self):
        persona = self.cleaned_data.get('persona')
        if not persona:
            raise forms.ValidationError('Por favor,selecciona un adoptante')
        return persona

    def clean_vacuna(self):
        vacuna = self.cleaned_data.get('vacuna')
        if not vacuna:
            raise forms.ValidationError('Por favor,elige una vacuna')
        return vacuna

    def __init__(self, *args, **kwargs):
        super(MascotaForm, self).__init__(*args, **kwargs)
        self.fields['persona'].choices = [(" ","Selecciona")]+[(persona.id,persona.nombre) for persona in Persona.objects.all()]

refugio/apps/mascota/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse

from django.core.urlresolvers import reverse_lazy

from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.contrib import messages

from apps.mascota.forms import MascotaForm
from apps.mascota.models import Mascota
from django.contrib.messages.views import SuccessMessageMixin


def index(request):
	return render(request, 'mascota/index.html')

def mascota_view(request):
	if request.method == 'POST':
		form = MascotaForm(request.POST,request.FILES)
		if form.is_valid():
			form.save()
			messages.add_message(request=request, level=messages.SUCCESS, message='La mascota ha sido agregada')
			return redirect('mascota_lista')
	else :
		form =MascotaForm()
	return render(request,'mascota/mascota_form.html',{'form':form})

	

def mascota_list(request):
	mascota = Mascota.objects.all().order_by('id')
	contexto = { 'mascotas':mascota}
	return render(request, 'mascota/mascota_listar.html', contexto)

def mascota_edit(request, id_mascota):
	mascota = Mascota.objects.get(id=id_mascota)
	if request.method == 'GET':
		form = MascotaForm(instance=mascota)
	else:
		form = MascotaForm(request.POST, instance=mascota)
		if form.is_valid():
			form.save()
			messages.add_message(request=request, level=messages.SUCCESS, message='Tus modificacciones han sido guardadas')
		return redirect('mascota_lista')
	return render(request, 'mascota/mascota_form.html', {'form':form})

def mascota_delete(request, id_mascota):
	mascota = Mascota.objects.get(id=id_mascota)
	if request.method == 'POST':
		mascota.delete()
		messages.add_message(request=request, level=messages.ERROR, message='La mascota ha sido eliminada')
		return redirect('mascota_lista')
	return render(request, 'mascota/mascota_eliminar.html', {'mascota':mascota})


class MascotaList(ListView):
	model = Mascota
	template_name = 'mascota/mascota_list.html'
	ordering = ['id']

class MascotaCreate(SuccessMessageMixin, CreateView):
	model = Mascota
	form_class = MascotaForm
	template_name = 'mascota/mascota_form.html'
	success_url = reverse_lazy('mascota_listar')

	def form_valid(self, form):
		messages.success(self.request, 'Nueva mascota agregada')
		return super().form_valid(form)

class MascotaUpdate(SuccessMessageMixin, UpdateView):
	model = Mascota
	form_class = MascotaForm
	template_name = 'mascota/mascota_form.html'
	success_url = reverse_lazy('mascota_listar')

	def form_valid(self, form):
		messages.success(self.request, 'la mascota ha sido actualizada')
		return super().form_valid(form);

class MascotaDelete(DeleteView):
    model = Mascota
    form_class = MascotaForm
    template_name = 'mascota/mascota_delete.html'
    success_url = reverse_lazy('mascota_listar')
        
    def delete(self, request, *args, **kwargs):
        messages.error(self.request, 'la mascota fue eliminada')
        return super().delete(request,*args, **kwargs)

refugio/templates/mascota/index.html
{% extends 'base/base.html'%}

{% block title %}
App Mascota
{% endblock %}

{% block header%}
<h4> Este es el header index Mascota</h4>
{% endblock %}

{% block content%}
<h5> Este es el contenido de Macota</h5>
{% endblock %}	

{% block footer%}
<h5> Aqui esta el footer de Mascota</h5>
{% endblock %}

refugio/templates/mascota/mascota_delete.html
{% extends 'base/base.html' %}

{% block content %}
<h2> Eliminar mascotas utilizando Clases </h2>
<form method="post">
	{% csrf_token %}
	<h3> ¿Esta seguro que desa eliminar el registro: {{object.nombre}}?</h3>
	<button class="btm btn-danger" type="submit">Confirmar</button>	
	<a class="btn btn-default" href="{% url 'mascota_listar' %}">Cancelar</a>
</form>

{% endblock %}

refugio/templates/mascota/mascota_eliminar.html
{% extends 'base/base.html' %}

{% block content %}
<h2>Eliminar registro utilizando Funciones </h2>
<form method="post">
	{% csrf_token %}
	<h3> ¿Esta seguro que desea eliminar el registro: {{mascota.nombre}}?</h3>
	<button class="btm btn-danger" type="submit">Confirmar</button>	
	<a class="btn btn-default" href="{% url 'mascota_lista' %}">Cancelar</a>
</form>

{% endblock %}

refugio/templates/mascota/mascota_form.html
{% extends 'base/base.html' %}

{% block content %}
<h1>Registra una mascota</h1>

{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="alert-alert-{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

	<form class="was-validated" method="post" enctype="multipart/form-data" novalidate>
		{% csrf_token %}
		{{ form.as_p }}
      <button class="btn-info-enviar" type="submit"> Guardar</button>	
	</form>
     <script type="text/javascript">

     jQuery.datetimepicker.setLocale('es');
    

 jQuery('#id_fecha_rescate').datetimepicker({
 i18n:{
  es:{
   months:[
    'Enero','Febrero','Marzo','Abril',
    'Mayo','Junio','Julio','Agosto',
    'Septiembre','Octubre','Noviembre','Diciembre',
   ],
   dayOfWeek:[
    "Domingo.", "Lunes", "Martes", "Miercoles",
    "Jueves", "Viernes", "Sabado",
   ]
  }
 },
 timepicker:false,
 format:'Y-m-d',
 lang:'en'
});
     </script>


{% endblock %}

refugio/templates/mascota/mascota_list.html
{% extends 'base/base.html' %}

{% block content %}
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="alert-alert-{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

<h2>Lista de mascotas Clases</h2>
<table class="table table-hover">
	<thead>
		<tr class="titletabla">
			<td>#</td>
			<td>Nombre</td>
			<td>Sexo</td>
			<td>Edad</td>
			<td>Fecha de rescate</td>
			<td>Adoptante</td>
            <td>Imagen</td>
			<td>Acciones</td>
		</tr>
	</thead>
	<tbody>
		{% if object_list %}
		{% for mascota in object_list %}
		<tr>
			<td>{{mascota.id}}</td>
			<td>{{mascota.nombre}}</td>
			<td>{{mascota.sexo}}</td>
			<td>{{mascota.edad_aproximada}}</td>
			<td>{{mascota.fecha_rescate}}</td>
			<td>{{mascota.persona.nombre}} {{mascota.persona.apellido}}</td>
            <td>
                {% if mascota.imagen %}
                <img class="img-mascota" src="{{ mascota.imagen.url }}" alt="Imagen-mascota" />
                {% else %}
                <img class="img-mascota" src="{{ MEDIA_URL }}imagenes_mascota/default.png" alt="No se encontro imagen" />
                {% endif %}
           </td>
               <!--<img src="{{ model_instance.image_field.url }}" alt="Image"></td>-->
			<td>
				<a class="btn btn-primary" href="{% url 'mascota_editar' mascota.id %}">Editar</a>
				<a class="btn btn-primary" href="{% url 'mascota_delete' mascota.id %}">Eliminar</a>
			</td>
		</tr>
		{% endfor %}

		{% else %}	
		<h1> No se encontaron registros de mascotas</h1>
	    {% endif %}
	</tbody>
</table>

{% endblock %}

refugio/templates/mascota/mascota_listar.html
{% extends 'base/base.html' %} {% block content %}
<br>

{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="alert-alert-{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

<h2>Lista de Mascota Funciones</h2>



<table class="table table-hover">
        <thead>
                <tr class="titletabla">
                        <th>#</th>
                        <th>Nombre</th>
                        <th>Sexo</th>
                        <th>Edad</th>
                        <th>Fecha de rescate</th>
                        <th>Adoptante</th>
                        <th>Acciones</th>
                </tr>
        </thead>
        <tbody>
                        {% if mascotas %}
                        {% for mascota in mascotas %}
                <tr>
                        <td>{{mascota.id}}</td>
                        <td>{{mascota.nombre}}</td>
                        <td>{{mascota.sexo}}</td>
                        <td>{{mascota.edad_aproximada}}</td>
                        <td>{{mascota.fecha_rescate}}</td>
                        <td>{{mascota.persona.nombre}} {{mascota.persona.apellidos}}</td>
                        <td>
                            <img class="img-mascota" src="{{mascota.imagen.url }}" alt="Imagen-mascota">
                        </td>
                        <td>
                                        <a href="{% url 'mascota_modificar' mascota.id %}" class="btn btn-primary">Editar</a>
                                        <a href="{% url 'mascota_eliminar' mascota.id %}" class="btn btn-danger">Eliminar</a>
                        </td>
                </tr>
                {% endfor %}
                {% else %}
                <h1>No hay registros de mascotas por funciones</h1>
                
                {% endif %}
        </tbody>
</table>
{% endblock %}